spring:
  thymeleaf:
    cache: false
  resources:
    cachePeriod: 3600

application:
  ha: true
  url: http://localhost
  security:
    fetchUserInfo: true
  baseImageUrl: ${application.url}/media
  defaultIconUrl: ${application.url}/img/noicon.png

web:
  home: http://www.ozwillo-dev.eu

kernel:
  base_uri: http://kernel.ozwillo-dev.eu
  alt_uri: http://accounts.ozwillo-dev.eu
  auth:
    issuer: ${kernel.base_uri}/
    auth_endpoint: ${kernel.alt_uri}/a/auth
    token_endpoint: ${kernel.base_uri}/a/token
    keys_endpoint: ${kernel.base_uri}/a/keys
    userinfo_endpoint: ${kernel.base_uri}/a/userinfo
    profile_endpoint: ${kernel.base_uri}/d/user
    password_change_endpoint: ${kernel.base_uri}/a/password
    revoke_endpoint: ${kernel.base_uri}/a/revoke
    logout_endpoint: ${kernel.alt_uri}/a/logout
    callback_uri: ${application.url}/callback
  user_directory_endpoint: ${kernel.base_uri}/d
  event_bus_endpoint: ${kernel.base_uri}/e
  notifications_endpoint: ${kernel.base_uri}/n
  client_id: portal
  client_secret: 8eAhg4X6HXpSlS/HPsdj6HmcjcwjRYn3gwwv6Z7SaP4
  scopes_to_require: openid profile email address

  portal_endpoints:
    subscriptions: ${kernel.base_uri}/apps/subscriptions
    catalog: ${kernel.base_uri}/m
    apps: ${kernel.base_uri}/apps


persistence:
  mongodatabase: portal
  mongohosts:
    - localhost
  login: portal
  password: portal
