spring:
  thymeleaf:
    cache: false
  resources:
    cachePeriod: 3600

ha:
  enabled: false
  nodes: n1:localhost:11211,n2:192.168.56.102:11211
  failover: n1

application:
  url: http://localhost:8080
  security:
    fetchUserInfo: true
    # requires devmode, to ease up development ex. of Catalog only
    noauthdevmode: false
  baseImageUrl: ${application.url}/media
  defaultIconUrl: ${application.url}/img/noicon.png
  store:
    load_size: 20
    # don't enable it until applications have filled the supported_locales field
    # (and even then it's better supported by UI sidebar's dropdown being inited to current locale)
    addCurrentToSupportedLocalesIfNone: false
  geoarea:
    project: geo_1
    areaModel: geo:Area_0
    primaryNameField: odisp:name
    secondaryNameField: geo:name
    geoCityModel: geoci:City_0
    cityField: geoci:name
    geoCountryModel: geoco:Country_0
    countryField: geoco:name
    displayNameField: odisp:name
    fallbackLanguage: en
    #use: Seconds | Min | Hour | Day-of-month | Month | Day-of-week(sunday=0) | Year = http://www.quartz-scheduler.org/documentation/quartz-1.x/tutorials/crontrigger
    replication: 0 0 1 1/5 * ?  #Runs at 1am every 5 days every month, starting on the first day of the month
    #replication: 0 0/1 * * * ?     #Runs every minute
  dcOrg:
    project: org_1
    orgModel: org:Organization_0
    baseUri: http://data.ozwillo.com/dc/type
  dcOrgSearch:
    sector: org:sector
    legalName: org:legalName.v
    regNumber: org:regNumber
    country: adrpost:country
  organizationDaysTillDeletedFromTrash: 7
  applicationInstanceDaysTillDeletedFromTrash: 7

# some switches:
# devmode = show debug tools (app deprovisioning, etc.) + do not minify / compress javascript
# production = include piwik js
# notificationsEnabled = enable notifications
# at some point we should use these as default values & instead look for the values in the database
# (to allow live switching of feature flags)
  devmode: false
  production: false
  notificationsEnabled: true

web:
  home: https://www.ozwillo-dev.eu
  sitemap:
      # TODO Change it with the prod version url
      #url_header: https://www.ozwillo.com/header.xml
      url_header: https://portal.ozwillo.com/xml/header_backup.xml
      url_footer: https://www.ozwillo.com/footer.xml
      #url_footer: https://portal.ozwillo.com/xml/footer_backup.xml
      refresh: 0 0 1 1/5 * ?  #Runs at 1am every 5 days every month, starting on the first day of the month
  # avatar file names below img/my/avatar/ (walking File tree wouldn't work in jar) :
  avatarPath: img/my/avatar
  # only for 64x64 pngs which should be mostly below 5000B
  maxUploadSize: 20000

rest:
  # by default uses mere HttpURLConnection, better : https://jira.spring.io/browse/ANDROID-54 http://stackoverflow.com/questions/25698072/simpleclienthttprequestfactory-vs-httpcomponentsclienthttprequestfactory-for-htt
  # instead of using Apache HTTPComponents Client (would require specific conf for enabling SNI, which should be possible since 4.3.2)
  revertToApacheHttpComponentsClient: false

kernel:
  base_uri: http://kernel.ozwillo-dev.eu
  alt_uri: ${kernel.base_uri}
  auth:
    issuer: ${kernel.base_uri}/
    auth_endpoint: ${kernel.alt_uri}/a/auth
    token_endpoint: ${kernel.base_uri}/a/token
    keys_endpoint: ${kernel.base_uri}/a/keys
    userinfo_endpoint: ${kernel.base_uri}/a/userinfo
    profile_endpoint: ${kernel.base_uri}/d/user
    password_change_endpoint: ${kernel.alt_uri}/a/password
    revoke_endpoint: ${kernel.base_uri}/a/revoke
    logout_endpoint: ${kernel.alt_uri}/a/logout
    callback_uri: ${application.url}/callback
    home_uri: ${application.url}/my
  user_directory_endpoint: ${kernel.base_uri}/d
  event_bus_endpoint: ${kernel.base_uri}/e
  notifications_endpoint: ${kernel.base_uri}/n
  client_id: portal
  client_secret: 7706ded0-afe4-4826-9df1-ce03782b893d
  # NB. once Datacore cache is in place, move datacore scope to its dedicated system user
  scopes_to_require: openid profile email address phone datacore
  maxUserMembershipsPerPage: 20
  portal_endpoints:
    subscriptions: ${kernel.base_uri}/apps/subscriptions
    catalog: ${kernel.base_uri}/m
    apps: ${kernel.base_uri}/apps

datacore:
  #url: http://localhost:8080
  url: https://plnm-dev-dc             # dev, requires installing gen'd cert, and (MUST) set the ip in /etc/hosts
  #url: https://data.ozwillo-dev.eu    # dev, doesn't work with current gen'd cert
  # alt_uri ??
  systemAdminUser:  #Get it using Node.js lib / with portal clientId
    refreshToken: oxNDM3NDY5MjQ4OTUyLCJleHjkyNDg5NTJ9eyJpZCI6Ijk2Y2IxY2IyLTU1YWEtNDYyZC04NGNmLTVlMTAyMjAzNWVmZS8wTHZsNTdXNlliYWtwSWVuZHQ0UVhnIiwiaWF0IjAiOjMwMTQyN
    nonce: 970774665428326      #Set it when getting the refreshToken


persistence:
  mongodatabase: portal
  mongohosts:
    - localhost
#  login: portal
#  password: portal


cache:
  hosts:
    - 192.168.56.1
    - 192.168.56.102
